openapi: "3.0.1"
info:
  title: "http-crud-tutorial-api"
  version: "2025-03-05 19:11:46UTC"
servers:
- url: "https://ucn9prowa5.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /items:
    get:
      responses:
        default:
          description: "Default response for GET /items"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:736301519450:function:http-crud-tutorial-function/invocations"
        connectionType: "INTERNET"
    put:
      responses:
        default:
          description: "Default response for PUT /items"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:736301519450:function:http-crud-tutorial-function/invocations"
        connectionType: "INTERNET"
    post:
      responses:
        default:
          description: "Default response for POST /items"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:736301519450:function:http-crud-tutorial-function/invocations"
        connectionType: "INTERNET"
    delete:
      responses:
        default:
          description: "Default response for DELETE /items"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:736301519450:function:http-crud-tutorial-function/invocations"
        connectionType: "INTERNET"
  /items/{id}:
    delete:
      responses:
        default:
          description: "Default response for DELETE /items/{id}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:736301519450:function:http-crud-tutorial-function/invocations"
        connectionType: "INTERNET"
    parameters:
    - name: "id"
      in: "path"
      description: "Generated path parameter for id"
      required: true
      schema:
        type: "string"
components:
  x-amazon-apigateway-integrations:
    unusedIntegration_gnzelco:
      payloadFormatVersion: "2.0"
      type: "aws_proxy"
      httpMethod: "POST"
      uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:736301519450:function:http-crud-tutorial-function/invocations"
      connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
  - "*"
  allowHeaders:
  - "*"
  maxAge: 100
  allowCredentials: false
  allowOrigins:
  - "*"
  - "http://*"
  - "https://*"
x-amazon-apigateway-importexport-version: "1.0"
